name: PHP Standards
on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: PHP Coding Standards (PHP ${{ matrix.php-version }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.4']
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        coverage: none

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version

    - name: Get Composer Cache Directory
      id: composer-cache-dir
      run: |
        echo "DIR=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache PHP Dependencies
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache-dir.outputs.DIR }}
        key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('composer.lock') }}

    - name: Install PHP Dependencies
      run: |
        composer install --prefer-dist --no-progress --no-interaction

    - name: PHPCS cache
      uses: actions/cache@v4
      with:
        path: tests/cache
        key: ${{ runner.os }}-phpcs-${{ matrix.php-version }}-${{ hashFiles('plugin.php') }}

    - name: Run the tests
      run: |
        composer test:phpcs
        composer test:phpstan
      env:
        MYSQL_DATABASE: wordpress
        WP_TESTS_DB_PASS: root
